async fn test() -> Result<(), string> {
    return Result::Err("error");
}